### ISSUE TITLE
Cannot start watch

### ISSUE THREAD

**Issue by uloco** [ubiquits/ubiquits#142]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, post your question in the [gitter channel](https://gitter.im/ubiquits/ubiquits/)

**What features are related to this issue**
- [ ] Quick Start
- [ ] Application Lifecycle
- [x] CLI
- [ ] Configuration
- [ ] Controllers
- [ ] Database
- [ ] Dependency Injection
- [ ] Deployment
- [ ] Documentation
- [ ] Email
- [ ] Exceptions
- [ ] Logging
- [ ] Middleware
- [ ] Migrations
- [ ] Model Stores
- [ ] Models
- [ ] Queues
- [ ] Routing
- [ ] Seeding
- [ ] Services
- [ ] Testing
- [ ] Validation

**Do you want to request a *feature* or report a *bug*?**
- [ ] Feature
- [x] Bug
- [ ] Something else

**What is the current behavior?**

When running `u watch` the following error occurs:
```
[watch] Cleaning directories [ './lib' ]
[watch] tsc -p /home/umut/Source/github/diascope/diascope/tsconfig.server.json --pretty --diagnostics
/home/umut/Source/github/diascope/diascope/node_modules/@ubiquits/toolchain/cli/tasks/build.js:63
      cli.log(chalk.red(`Failed to run '${args}'.\n${code}`));
                                          ^

ReferenceError: args is not defined
    at ChildProcess.compiler.on (/home/umut/Source/github/diascope/diascope/node_modules/@ubiquits/toolchain/cli/tasks/build.js:63:43)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

`npm install -g @ubiquits/toolchain && u`
and follow the quick start.
When running `u watch` the error occurs

**What is the expected behavior?**

start serving the app

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- Ubiquits version: @ubiquits/toolchain@2.0.1-1
- NodeJS version: 6.9.1
- Browser: [all | Chrome xx | Firefox xx | IE xx | Safari xx ]
- OS:  Linux 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by zakhenry** [comment]
Hi @uloco, it looks like you've encountered a typescript compiler error, the stack trace was actually just hiding the error as there was an issue with the error handling referencing the wrong variable.

Please note as of yesterday, the ubiquits project has moved over to https://github.com/zerothstack/zeroth (http://zeroth.io) I just haven't yet gotten around to deprecating this repo. Sorry for the inconvenience, however the install process is still the same (it's just a name change).
